service: creme-brulee-bot

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DISCORD_BOT_TOKEN: ${env:DISCORD_BOT_TOKEN}
    DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
    DISCORD_APPLICATION_ID: ${env:DISCORD_APPLICATION_ID}

functions:
  discord:
    handler: bot.run_bot
    events:
      - http:
          path: /discord/interactions
          method: post
          cors: true
    timeout: 30
    memorySize: 256

package:
  patterns:
    - '!venv/**'
    - '!.env'
    - '!__pycache__/**'
    - '!.git/**' 