service: cremeai-bot

frameworkVersion: '4.7.0'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}

functions:
  bot:
    handler: lambda_function.lambda_handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: api/interactions
          method: post
          cors: true

package:
  patterns:
    - '!venv/**'
    - '!.env'
    - '!__pycache__/**'
    - '!.git/**'
    - '!tests/**'
    - lambda_function.py
    - services/**
    - requirements.txt

custom:
  pythonRequirements:
    layer:
      name: python-deps
      description: Python dependencies
    noDeploy:
      - coverage
      - pytest
      - pytest-mock
      - pytest-cov
    dockerizePip: true
    pipCmdExtraArgs:
      - --no-cache-dir

plugins:
  - serverless-python-requirements
